name: nowiki
label: Norwegian Wikipedia
host: no.wikipedia.org

external_samples:
  sampled_revisions.100k_2015:
    quarry_url: https://quarry.wmflabs.org/run/67250/output/0/json-lines?download=true
  human_labeled_revisions.5k_2019:
    labeling_campaign: https://labels.wmflabs.org/campaigns/nowiki/27/

autolabeled_samples:
  trusted_edits: 1000
  trusted_groups:
   - sysop
   - oversight
   - bot
   - rollbacker
   - checkuser
   - abusefilter
   - bureaucrat
  labeled_samples:
    autolabeled_revisions.100k_2015: sampled_revisions.100k_2015

balanced_5k_samples:
  revisions_for_review.5k_2015: autolabeled_revisions.100k_2015

random_samples:
  autolabeled_revisions.40k_2015:
    n: 40000
    input_name: autolabeled_revisions.100k_2015

merged_samples:
  labeled_revisions.100k_2015:
    - human_labeled_revisions.5k_2019
    - autolabeled_revisions.100k_2015

extracted_samples:
  labeled_revisions.w_cache.100k_2015.json:
    sample: labeled_revisions.100k_2015
    features_for:
      - damaging
      - goodfaith

models:
  damaging:
    observations: labeled_revisions.w_cache.100k_2015.json
    label: damaging
    pop_rate_true: 0.018525821674654473
    tune: true
    cv_train:
      algorithm: GradientBoosting
      build_number: 1
      parameters:
        learning_rate: 0.01
        max_depth: 7
        max_features: log2
        n_estimators: 500
  goodfaith:
    observations: labeled_revisions.w_cache.100k_2015.json
    label: goodfaith
    pop_rate_true: 0.9865927208557759
    tune: true
    cv_train:
      algorithm: GradientBoosting
      build_number: 1
      parameters:
        learning_rate: 0.01
        max_depth: 7
        max_features: log2
        n_estimators: 500 
