name: ptwiki
label: Portugueses Wikipedia
host: pt.wikipedia.org

samples:
    20k_2015:
        labeling_campaign: "https://labels.wmflabs.org/campaigns/ptwiki/7/"

default_sample: 20k_2015
review_sample: 20k_2015

merged_samples:
    20k_2015:
        human_labeled_revisions: "20k_2015"

models:
    damaging:
        pop_rate_true: 0.06896029864299047
    goodfaith:
        pop_rate_true: 0.9397669373959542

